# Generated by Django 3.0 on 2024-02-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('F', '女'), ('M', '男')], max_length=1, verbose_name='性别'),
        ),
    ]
