# Generated by Django 3.0 on 2024-02-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20240225_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[('2', '女'), ('1', '男')], max_length=1, verbose_name='性别'),
        ),
    ]
