# Generated by Django 3.0 on 2024-03-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('phone', models.CharField(max_length=15, verbose_name='电话')),
                ('license_plate_number', models.CharField(max_length=15, verbose_name='车牌号')),
                ('violation_count', models.PositiveIntegerField(default=0, verbose_name='违规次数')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='college',
            field=models.CharField(choices=[('ECE', '电子与计算机工程学院'), ('CE', '土木与交通工程学院'), ('EM', '经济管理学院'), ('ME', '机械与电气工程学院'), ('AAS', '建筑与艺术设计学院'), ('PCE', '制药与化学工程学院')], default='其他', max_length=50, verbose_name='学院信息'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='violation_count',
            field=models.PositiveIntegerField(default=0, verbose_name='违停次数'),
        ),
    ]
